// -*- mode: idl; indent-tabs-mode: t; tab-width: 4; c-basic-offset: 4; -*-


module OpenHRP {
	
	//enum ControlType { FORCE, POSITION };

	interface sonyService
	{
		void start();
		void setObjectV(in double x, in double y,in double z,in double roll,in double pitch,in double yaw);
		void testMove();
		void stepping();
		void stop();

		void setFootPosR();
		void setFootPosL();
		void setFootPosR2(in double x, in double y, in double z, in double r, in double p, in double w);
		void setFootPosL2(in double x, in double y, in double z, in double r, in double p, in double w);
	};
};
